### ISSUE TITLE
AttributeError: module 'modules.ui' has no attribute 'ToolButton'

### ISSUE THREAD

**Issue by jimi202008** [SkinnyDevi/webui_tavernai_charas#4]
Traceback (most recent call last):
  File "/mnt/d/wsl/text-generation-webui/server.py", line 230, in <module>
    create_interface()
  File "/mnt/d/wsl/text-generation-webui/server.py", line 140, in create_interface
    extensions_module.create_extensions_tabs()  # Extensions tabs
  File "/mnt/d/wsl/text-generation-webui/modules/extensions.py", line 200, in create_extensions_tabs
    extension.ui()
  File "/mnt/d/wsl/text-generation-webui/extensions/webui_tavernai_charas/script.py", line 29, in ui
    charas_ui.mount_ui()
  File "/mnt/d/wsl/text-generation-webui/extensions/webui_tavernai_charas/ui/main.py", line 23, in mount_ui
    featured_ui()
  File "/mnt/d/wsl/text-generation-webui/extensions/webui_tavernai_charas/ui/featured.py", line 424, in featured_ui
    mount_fixed_categories()
  File "/mnt/d/wsl/text-generation-webui/extensions/webui_tavernai_charas/ui/featured.py", line 263, in mount_fixed_categories
    create_tavernai_chara_display(
  File "/mnt/d/wsl/text-generation-webui/extensions/webui_tavernai_charas/ui/featured.py", line 89, in create_tavernai_chara_display
    refresh_button = ui.ToolButton(
AttributeError: module 'modules.ui' has no attribute 'ToolButton'
The extension needs to be updated

**Comment by Mayhem50** [comment]
same

**Comment by murkinhustla** [comment]
same

**Comment by SkinnyDevi** [comment]
@jimi202008 could you provide more information on how you updated your webui?

I had some initial problems updating, but after a clean re-install of the webui and re-installed the extension through the "Session" tab I could get the extension to work again.

**Comment by SkinnyDevi** [comment]
I have pushed an update. Please update your extensions and comment if it works to close this issue.

**Comment by SkinnyDevi** [comment]
I will now close this issue as this has been resolved, and no further issues related have arised.
