### ISSUE TITLE
Cant load

### ISSUE THREAD

**Issue by Steelman14aUA** [SkinnyDevi/webui_tavernai_charas#5]
2023-12-18 03:34:00 INFO:Loading the extension "webui_tavernai_charas-master"...
2023-12-18 03:34:00 ERROR:Failed to load the extension "webui_tavernai_charas-master".
Traceback (most recent call last):
  File "E:\Ai\Oobabooga\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1
    import extensions.webui_tavernai_charas-master.script
                                           ^
SyntaxError: invalid syntax

**Comment by SkinnyDevi** [comment]
Thank you for reporting this error!

I'll have a look at it during the following days and come back with a fix.

**Comment by SWEet22222** [comment]
I too have the same issue
```py
04:36:54-222510 INFO     Loading the extension "gallery"
04:36:54-224961 INFO     Loading the extension "whisper_stt"
04:36:54-227440 INFO     Loading the extension "webui_tavernai_charas"
04:36:54-229921 INFO     Loading the extension "alltalk_tts-main"
04:36:54-248914 ERROR    Failed to load the extension "alltalk_tts-main".
Traceback (most recent call last):
  File "E:\oobabooga\text-generation-webui\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1
    import extensions.alltalk_tts-main.script
                                 ^
SyntaxError: invalid syntax
```

**Comment by SkinnyDevi** [comment]
@Steelman14aUA @Oridjinn1980
Hi there. First, sorry for the late response.  Second, has your issue been resolved? If not try and update the text generation webUI top the latest version. I just updated and the extension seems to work with no problems present.

If the problem did resolve, please close the issue
